version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: koa-better-error-handler
    versions:
    - 6.0.1
    - 7.0.0
