# ESLint config

root: true
env:
  node: true
  jest: true
  es6: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  no-console: warn
  semi: ['error', 'never']
