version: '3.4'
services:

  app:
    build:
      context: .
      target: dev
    image: jwt-api:dev
    volumes:
      - '.:/opt/app'
      - node_modules:/opt/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - APP_URL=localhost:3000
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  node_modules:
    driver: local
