version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: jwt-api_base:latest
    volumes:
      - '.:/opt/app'
      - node_modules:/opt/app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

volumes:
  node_modules:
    driver: local
