version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "security"
    default_labels:
      - "dependencies"
